poky-agl.conf: Add polkit in DISTRO FEATURES
ERROR: Nothing RPROVIDES 'udisks'
udisks was skipped: missing required distro feature 'polkit'
(not in DISTRO_FEATURES)

Bug-AGL: SPEC-2932

Change-Id: I71660190c57cbc8adbe1be4d5468f1a38b49d3d5
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>