polkit-rule-agl-app: try to prevent transaction error
While creating the final filesystem we see this error in CI:
Running transaction test
Error: Transaction test error:
  file /etc/polkit-1/rules.d conflicts between attempted installs of polkit-rule-agl-app-1.0-r0.11.corei7_64 and polkit-0.119-r0.11.corei7_64

ERROR: Logfile of failure stored in: /w/workspace/release-jjb-pike-snapshot/MACHINE/qemux86-64/label/agl-test-slave/repoclone/output/tmp/work/qemux86_64-agl-linux/agl-demo-platform-crosssdk/1.0-r0/temp/log.do_rootfs.44779
NOTE: recipe agl-demo-platform-crosssdk-1.0-r0: task do_rootfs: Failed

Try to work this around.

Bug-AGL: SPEC-4837
Change-Id: I855bfe88651cc5e738630936639e599523eb811c
Signed-off-by: Jan-Simon Moeller <jsmoeller@linuxfoundation.org>
Reviewed-on: https://gerrit.automotivelinux.org/gerrit/c/AGL/meta-agl/+/29016
Tested-by: Jenkins Job builder account
ci-image-build: Jenkins Job builder account
ci-image-boot-test: Jenkins Job builder account